name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1

jobs:
  tests-pass:
    name: OK
    runs-on: ubuntu-latest
    needs:
      - wasm32-wasi
    steps:
      - run: exit 0

  wasm32-wasi:
    name: wasm32-wasi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust ${{ env.rust_stable }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1

      - name: Install wasm32-wasi target
        run: rustup target add wasm32-wasi

      # Compile
      - name: clean_and_build.sh
        run: bash clean_and_build.sh